import os
from typing import Optional

from dotenv import load_dotenv
from google import genai

# Load .env file
load_dotenv()


class GeminiDocumentGenerator:

    def __init__(self):
        # Read Gemini API key from .env
        self.api_key = os.getenv("GEMINI_API_KEY")

        # Model name
        self.model_name = "gemini-3.8-flash"

        # Whether API key exists
        self.api_key_configured = bool(self.api_key)

        # Demo mode = True when API key is missing
        self.demo_mode = not self.api_key_configured

        # Create Gemini client only when API key exists
        self.client = None

        if self.api_key_configured:
            self.client = genai.Client(api_key=self.api_key)

    def generate_document(
        self,
        document_type: str,
        parties: str,
        terms: str,
        effective_date: Optional[str] = None,
    ) -> str:

        if self.demo_mode:
            return self._generate_demo_document(
                document_type,
                parties,
                terms,
                effective_date,
            )

        prompt = f"""
You are a legal document drafting assistant.

Create a professional {document_type}.

Parties:
{parties}

Terms:
{terms}

Effective Date:
{effective_date or "Not specified"}

Requirements:
- Use clear and professional legal language.
- Organize the document with suitable headings.
- Include the parties and important terms.
- Do not invent important facts that were not provided.
- Return only the document text.
"""

        try:
            response = self.client.models.generate_content(
                model=self.model_name,
                contents=prompt,
            )

            if not response or not response.text:
                raise RuntimeError("Gemini returned an empty response.")

            return response.text

        except Exception as exc:
            raise RuntimeError(
                f"Gemini API request failed: {exc}"
            ) from exc

    def _generate_demo_document(
        self,
        document_type: str,
        parties: str,
        terms: str,
        effective_date: Optional[str] = None,
    ) -> str:

        return f"""
{document_type.upper()}

Effective Date: {effective_date or "Not specified"}

PARTIES

{parties}

TERMS AND CONDITIONS

{terms}

This document has been generated by LegalEase in demo mode.
""".strip()